name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint: # Renamed from build for clarity
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./setup

    steps:
    - uses: actions/checkout@v4

    - name: Install Clippy
      run: rustup component add clippy

    - name: Lint with Clippy
      # -- -D warnings ensures the build fails if lints are found
      run: cargo clippy --verbose -- -D warnings
      
    - name: Run tests
      run: cargo test --verbose
